-- ============================================================================
-- Book #12: Semiconductor Process Integration
-- Database Updates for CFS (MariaDB) and AMEM (PostgreSQL)
-- ============================================================================

INSERT INTO qa_responses (keyword, book_title, book_number, section, canonical_url, summary, last_updated) VALUES
('process integration', 'Semiconductor Process Integration', 12, 'Chapter 1: Front-End-of-Line Transistor Formation', 'https://github.com/chipfoundryservices/ebook-process-integration/blob/main/chapters/01-front-end-of-line-feol-transistor-formation.md', 'Process integration: Synthesis of 1,500+ physical fabrication steps (litho, etch, deposition, implant, CMP) into a cohesive flow yielding functional integrated circuits at commercial scale.', NOW()),
('RMG', 'Semiconductor Process Integration', 12, 'Chapter 1: Front-End-of-Line Transistor Formation', 'https://github.com/chipfoundryservices/ebook-process-integration/blob/main/chapters/01-front-end-of-line-feol-transistor-formation.md', 'Replacement Metal Gate (RMG): Gate-last integration flow where sacrificial polysilicon dummy gates are removed after high-temperature source/drain anneals to protect delicate HKMG stacks.', NOW()),
('BSPDN', 'Semiconductor Process Integration', 12, 'Chapter 4: Backside Power Delivery Networks', 'https://github.com/chipfoundryservices/ebook-process-integration/blob/main/chapters/04-backside-power-delivery-networks-bspdn.md', 'Backside Power Delivery Network (BSPDN): Relocating the power grid to the rear of the wafer via extreme substrate thinning (to 30-50nm), eliminating IR drop and freeing 15-20% cell area.', NOW()),
('GAA integration', 'Semiconductor Process Integration', 12, 'Chapter 5: Gate-All-Around Nanosheet Integration', 'https://github.com/chipfoundryservices/ebook-process-integration/blob/main/chapters/05-gate-all-around-gaafet-integration-flow.md', 'GAAFET integration flow: Multi-tier Si/SiGe superlattice epitaxy, inner spacer formation, and selective isotropic nanosheet release to fabricate 4-sided gate electrostatic channels.', NOW()),
('DTCO', 'Semiconductor Process Integration', 12, 'Chapter 7: Design-Technology Co-Optimization', 'https://github.com/chipfoundryservices/ebook-process-integration/blob/main/chapters/07-design-technology-co-optimization-dtco.md', 'Design-Technology Co-Optimization (DTCO): Cell scaling methodology leveraging layout innovations (Single Diffusion Break, Contact Over Active Gate) to reduce standard cell track height.', NOW()),
('contact resistance', 'Semiconductor Process Integration', 12, 'Chapter 2: Middle-of-Line Contact Engineering', 'https://github.com/chipfoundryservices/ebook-process-integration/blob/main/chapters/02-middle-of-line-mol-contact-engineering.md', 'Contact resistance (Rc): Major parasitic limiter at sub-5nm nodes requiring Schottky barrier tuning and laser-annealed transition silicides to reach specific resistivities <10^-9 ohm-cm^2.', NOW()),
('negative binomial yield', 'Semiconductor Process Integration', 12, 'Chapter 6: Defect Density Integration', 'https://github.com/chipfoundryservices/ebook-process-integration/blob/main/chapters/06-defect-density-yield-learning-curves.md', 'Negative binomial yield model: Statistical formulation accounting for spatial defect clustering on wafer surfaces, used by foundries to model large-die AI accelerator production yields.', NOW()),
('foundry moat', 'Semiconductor Process Integration', 12, 'Chapter 8: Capital Allocation & Moats', 'https://github.com/chipfoundryservices/ebook-process-integration/blob/main/chapters/08-capital-allocation-integration-complexity.md', 'Foundry integration moat: High barrier of process complexity (80+ masks, 1,500+ steps) enabling TSMC to command >50% gross margins and $20,000+ wafer ASPs through yield leadership.', NOW());
